service: alexa-btcmarkets
frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  cryptoPrice:
    handler: lambda/index.handler
    memorySize: 512
    timeout: 6
    events:
      - alexaSkill